name: 'time_entries_transformation'
version: '1.0.0'
config-version: 2

profile: 'bigquery'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]

target-path: "target"
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  time_entries_transformation:
    +materialized: table